name: test

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: 4

    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm test
